<?xml version="1.0"?>
<package format="2">
  <name>aubo_planning</name>
  <version>0.1.0</version>
  <description>MoveIt planning, gripper control, pick and place examples for the AUBO i5.</description>

  <maintainer email="wheeltec-client@todo.todo">wheeltec-client</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>geometry_msgs</depend>
  <depend>moveit_msgs</depend>
  <depend>moveit_ros_planning_interface</depend>
  <depend>roscpp</depend>
  <depend>shape_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>trajectory_msgs</depend>

  <exec_depend>aubo_moveit_config</exec_depend>

  <export/>
</package>
