min_particles: 300
max_particles: 1500
kld_err: 0.02
kld_z: 0.99
update_min_d: 0.10
update_min_a: 0.10
resample_interval: 1
transform_tolerance: 0.5
laser_max_beams: 60
laser_min_range: 0.12
laser_max_range: 11.5
laser_model_type: likelihood_field
laser_likelihood_max_dist: 2.0
odom_model_type: diff
odom_alpha1: 0.1
odom_alpha2: 0.1
odom_alpha3: 0.1
odom_alpha4: 0.1
odom_frame_id: odom
base_frame_id: base_footprint
global_frame_id: map
