controller_manager_ns: aubo_i5/controller_manager
controller_list:
  - name: aubo_i5/aubo_i5_controller      # 原来是 aubo_i5_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - shoulder_joint
      - upperArm_joint
      - foreArm_joint
      - wrist1_joint
      - wrist2_joint
      - wrist3_joint
